-- AlterTable
ALTER TABLE "MenuItem" ADD COLUMN     "imagePositionX" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "imagePositionY" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "imageScale" DOUBLE PRECISION NOT NULL DEFAULT 1;
